apiVersion: v2
name: cloud-provider-equinix-metal
description: Kubernetes Cloud Provider for Equinix Metal
type: application
version: "0.1.0"
appVersion: "main"
home: https://metal.equinix.com
sources:
  - https://sigs.k8s.io/cloud-provider-equinix-metal
