apiVersion: v1
kind: Secret
metadata:
  name: metal-cloud-config
  namespace: kube-system
stringData:
  cloud-sa.json: |
    {
      "apiKey": "Equinix Metal auth token",
      "projectID": "Equinix Metal project id"
    }
