{{ if .Values.configSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provider-equinix-metal.configSecretName" . }}
  labels:
    {{- include "cloud-provider-equinix-metal.labels" . | nindent 4 }}
type: Opaque
data:
  cloud-sa.json: {{ .Values.config | toJson | b64enc | quote }}
{{ end }}