name: Continuous Integration
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - master

env:
  IMAGE_NAME: "equinix/cloud-provider-equinix-metal"

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }}
    - name: event_name
      run: echo ${{ github.event_name }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17' # The Go version to download (if necessary) and use.
    - name: ci
      run: make ci
    - name: Set up QEMU for cross-building
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ${{env.IMAGE_NAME}}:${{github.sha}}

    # the rest of these only are used if we push to master
    - name: Login to DockerHub
      if: github.event_name == 'push' && endsWith(github.ref,'/master')
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push  # theoretically, this builds what we did before, but with an unchanged dockerfile, it will just find everything in cache
      id: docker_push
      if: github.event_name == 'push' && endsWith(github.ref,'/master')
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{env.IMAGE_NAME}}:${{github.sha}}
          ${{env.IMAGE_NAME}}:master
